urls.py
from django.conf.urls import patterns, url
from django.conf import settings
from django.conf.urls.static import static

import views

urlpatterns = patterns('',
                       # Access pages
                       url(r'^$', views.index, name='viewer_index'),
                       url(r'^register/$', views.register, name='viewer_register'),
                       url(r'^login/$', views.user_login, name='viewer_login'),
                       url(r'^logout/$', views.user_logout, name='viewer_logout'),
                       url(r'^restricted/$', views.restricted,
                           name='viewer_restricted'),
                       url(r'^users/change-password/', 'django.contrib.auth.views.password_change',
                           {
                               'template_name': 'viewer/user/change_password.html',
                               'post_change_redirect': '/viewer/users/change-password-done/',
                           }, name='viewer_change_password'),
                       url(r'^users/change-password-done/', 'django.contrib.auth.views.password_change_done',
                           {
                               'template_name': 'viewer/user/change_password_done.html'
                           }, name='change-password-done'),

                       url(r'^populate-sidebar/$', views.populate_sidebar, name='populate_sidebar'),

                       # Errors
                       url(r'^error/no_project/$', views.no_project, name='no_project'),
                       # Project
                       url(r'^project/$', views.manage_project,
                           name='manage_project'),
                       url(r'^project/new_project/$',
                           views.new_project, name='new_project'),
                       url(r'^project/edit_project/(?P<project_id>\d+)/$',
                           views.edit_project, name='edit_project'),
                       url(r'^get_all_projects/$', views.get_all_projects,
                           name='get_all_projects'),


                       # Bnid
                       url(r'^get_bnids_by_study/(?P<study_id>\d+)/$',
                           views.get_bnids_by_study, name='get_bnids_by_study'),
                       url(r'^get_studies/$',
                           views.get_studies, name='get_studies'),

                       # Sample
                       url(r'delete_sample/(?P<sample_id>\d+)/$', views.delete_sample,
                           name='delete_sample'),
                       url(r'^get_samples/(?P<study_id>\d+)/$', views.get_samples,
                           name='get_samples'),

                       # Metadata
                       url(r'^metadata/$', views.manage_metadata, name='manage_metadata'),
                       url(r'^metadata/(?P<set_viewing_project_pk>\d+)/$', views.manage_metadata,
                           name='manage_metadata_set_viewing_project_pk'),
                       url(r'^metadata/new_metadata/$', views.new_metadata, name='new_metadata'),
                       url(r'^metadata/edit_metadata/(?P<sample_id>\d+)/$',
                           views.edit_metadata, name='edit_metadata'),

                       # Status
                       url(r'^status/$', views.manage_status, name='manage_status'),
                       url(r'^status/update_status/$', views.update_status, name='update_status'),
                       url(r'^status/check_status/$', views.check_status, name='check_status'),
                       url(r'^status/get_all_statuses/$', views.get_all_statuses, name='get_all_statuses'),
                       url(r'^status/get_stats/(?P<dname>\w+)/(?P<bnid>\d+-\d+)/$', views.get_stats, name='get_stats'),
                       url(r'^status/ajax_rows/(?P<start>\d+)/(?P<stop>\d+)/$', views.manage_status_ajax_rows,
                           name='manage_status_ajax_rows'),

                       # Study
                       url(r'^study/$', views.manage_study, name='manage_study'),
                       url(r'^study/(?P<set_viewing_project_pk>\d+)$', views.manage_study,
                           name='manage_study_set_viewing_project_pk'),
                       url(r'^study/new_study/$', views.new_study, name='new_study'),
                       url(r'^study/edit_study/(?P<study_id>\d+)/$',
                           views.edit_study, name='edit_study'),
                       url(r'^study/delete_study/(?P<study_id>\d+)/$',
                           views.delete_study, name='delete_study'),

                       # Report
                       # url(r'^report/$', views.manage_report,
                       #     name='manage_report'),
                       # url(r'^report/(?P<set_viewing_project_pk>\d+)/$', views.manage_report,
                       #     name='manage_report_set_viewing_project_pk'),
                       # url(r'^report/ajax_rows/(?P<start>\d+)/(?P<stop>\d+)/$', views.manage_report_ajax_rows,
                       #     name='manage_report_ajax_rows'),
                       # url(r'^report/edit_report/(?P<report_id>\d+)/$',
                       #     views.edit_report, name='edit_report'),
                       # url(r'report/view_report/(?P<file_id>\d+)/$',
                       #     views.view_report, name='view_report'),
                       # url(r'^report/upload_report/$', views.upload_report,
                       #     name='upload_report'),
                       # url(r'^report/delete_report/(?P<report_id>\d+)/$', views.delete_report,
                       #     name='delete_report'),
                       # url(r'^load_variants/(?P<report_id>\d+)/$', views.load_variants,
                       #     name='load_variants'),
                       # url(r'^report/zip-and-download/', views.zip_and_download, name='zip_and_download'),
                       # url(r'^report/get_info/$', views.report_info_get, name='report_info_get'),
                       #
                       # # Share
                       # url(r'^shared/view/(?P<shared_data_uuid>[\da-f\-]+)/$', views.view_shared_data,
                       #     name='view_shared_data'),
                       # url(r'^shared/share_report/$', views.share_report, name='share_report_post'),
                       # # url(r'^shared/share_report/(?P<report_id>\d+)/$', views.share_report, name='share_report'),
                       # url(r'^error/shared_data_expired/$',
                       #     views.view_share_data_expired, name='shared_data_expired'),
                       # url(r'^error/shared_data_dne/$', views.view_share_data_dne, name='shared_data_dne'),
                       #
                       # url(r'^files/(?P<path>.*)$',
                       #     'django.views.static.serve',
                       #     {'document_root': settings.MEDIA_ROOT}),

                       # Contact
                       url(r'^contact/$', views.manage_contact,
                           name='manage_contact'),
                       url(r'^contact/(?P<set_viewing_project_pk>\d+)/$', views.manage_contact,
                           name='manage_contact_set_viewing_project_pk'),
                       url(r'^contact/new_contact/$', views.new_contact,
                           name='new_contact'),
                       url(r'^contact/new_contact_from_share/$', views.new_contact_from_share,
                           name='new_contact'),
                       url(r'^contact/edit_contact/(?P<contact_id>\d+)/$', views.edit_contact,
                           name='edit_contact'),
                       url(r'^contact/delete_contact/(?P<contact_id>\d+)/$', views.delete_contact,
                           name='delete_contact'),
                       url(r'^contact/get_contacts_json/(?P<project_id>\d+)/$', views.get_contacts_json,
                           name='get_contacts'),

                       # Search
                       # url(r'^search/$', views.search_reports, name='search_reports'),
                       # url(r'^search/(?P<set_viewing_project_pk>\d+)/$', views.search_reports,
                       #     name='search_reports_set_viewing_project_pk'),
                       # url(r'^ajax_search_reports/(?P<search_col>\S+)/(?P<search_term>\S+)/(?P<search_type>\S+)/$',
                       #     views.ajax_search_reports, name='ajax_search_reports'),
                       # url(r'^ajax_search_reports/(?P<search_col>\S+)/(?P<search_term>\S+)/(?P<search_type>\S+)/(?P<reports_ids>\S+)/$',
                       #     views.ajax_search_reports, name='ajax_search_reports'),
                       #
                       #
                       # # Info
                       # url(r'^info/$', views.info_many, name='info_many'),
                       # url(r'^info/(?P<report_id>\d+)/$', views.info, name='info'),
                       # url(r'^cards/get/$', views.get_cards, name='get_cards'),
                       # # url(r'^cards/gene/(?P<report_id>\d+)/$', views.cards, name='cards_report'),
                       # url(r'^get_series_data/$', views.get_series_data, name='get_series_data')
                       #
                       ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

models.py
import datetime

from django.contrib.auth.models import User
from django.db import models
from uuidfield import UUIDField


class Project(models.Model):
    name = models.CharField(max_length=64, verbose_name="Project Name")
    description = models.CharField(max_length=2048,
                                   verbose_name="Project Description", blank=True)
    creation_date = models.DateTimeField('Date Created', auto_now=True,
                                         blank=True)
    user = models.ManyToManyField(User, blank=True,
                                  verbose_name="Project User")

    def __unicode__(self):
        return self.name


class Study(models.Model):
    name = models.CharField(max_length=64, verbose_name="Study Name", unique=True)
    project = models.ForeignKey(Project)
    description = models.CharField(max_length=256,
                                   verbose_name="Study Description",
                                   blank=True)
    creation_date = models.DateTimeField('Date Created', auto_now=True,
                                         blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Studies'


class Caller(models.Model):
    name = models.CharField(max_length=64, verbose_name="Caller Name")

    def __str__(self):
        return self.name


class Genome(models.Model):
    name = models.CharField(max_length=64, verbose_name="Genome")

    def __str__(self):
        return self.name


class Sample(models.Model):
    name = models.CharField(max_length=48, verbose_name='Sample Name', unique=True)
    description = models.CharField(max_length=256,
                                   verbose_name="Sample Description",
                                   blank=True)
    cellularity = models.CharField(max_length=8, verbose_name='% Cellularity',
                                   blank=True)
    study = models.ForeignKey(Study)
    creation_date = models.DateTimeField('Date Created', auto_now=True,
                                         blank=True)

    def __str__(self):
        return str(self.name)


class Bnid(models.Model):
    sample = models.ForeignKey(Sample)
    bnid = models.CharField(max_length=12, verbose_name='Bionimbus ID')
    description = models.CharField(max_length=256, verbose_name='Description',
                                   blank=True)
    library_type = models.CharField(max_length=32, verbose_name='Sequencing library type', blank=True)
    creation_date = models.DateTimeField('Date Created', auto_now=True,
                                         blank=True)

    def __str__(self):
        return '{} ({})'.format(str(self.sample), str(self.bnid))


# class Report(models.Model):
#     caller = models.ForeignKey(Caller)
#     study = models.ForeignKey(Study)
#     name = models.CharField(max_length=256, verbose_name='Report Name', default='report')
#     genome = models.ForeignKey(Genome, default=1, blank=True)
#     upload_date = models.DateTimeField('Date Uploaded', auto_now=True)
#     bnids = models.ManyToManyField(Bnid, verbose_name='Bionimbus ID', blank=True)
#     report_file = models.FileField('Report File', upload_to='', blank=True,
#                                    null=True)
#
#     def show_bnids(self):
#         return "_".join([a.bnid for a in self.bnids.all()])
#
#     def __str__(self):
#         return str(self.report_file)


# class Variant(models.Model):
#     report = models.ForeignKey(Report)
#     chrom = models.CharField(max_length=24, verbose_name='Chrom')
#     pos = models.IntegerField(verbose_name='Position', null=True)
#     ref = models.CharField(max_length=256, verbose_name='Reference Allele',
#                            blank=True, null=True)
#     alt = models.CharField(max_length=256, verbose_name='Alternate Allele',
#                            blank=True, null=True)
#     normal_ref_count = models.IntegerField(verbose_name='Normal Ref Count',
#                                            blank=True, null=True)
#     normal_alt_count = models.IntegerField(verbose_name='Normal Alt Count',
#                                            blank=True, null=True)
#     pct_normal_alt = models.FloatField(verbose_name='%_Normal_Alt',
#                                        blank=True, null=True)
#     tumor_ref_count = models.IntegerField(verbose_name='Tumor Ref Count',
#                                           blank=True, null=True)
#     tumor_alt_count = models.IntegerField(verbose_name='Tumor Alt Count',
#                                           blank=True, null=True)
#     pct_tumor_alt = models.FloatField(verbose_name='%_Tumor_Alt',
#                                       blank=True, null=True)
#     tn_pct_alt_ratio = models.FloatField(verbose_name='T/N % alt ratio',
#                                          blank=True, null=True)
#     gene_name = models.CharField(max_length=32, verbose_name='Gene Name',
#                                  blank=True, null=True)
#     extra_info = models.CharField(verbose_name='Extra Info', blank=True,
#                                   null=True, max_length=20000)
#
#     def __str__(self):
#         return "{}:{}{}>{}".format(self.chrom, self.pos, self.ref, self.alt)


class Contact(models.Model):
    full_name = models.CharField(max_length=256, verbose_name='Full Name')
    email = models.EmailField(verbose_name='Email')
    project = models.ForeignKey(Project, verbose_name='Project',
                                blank=True, null=True)

    def __unicode__(self):
        return '"{}" <{}>'.format(self.full_name, self.email)


class SharedData(models.Model):
    name = models.CharField(max_length=128, verbose_name='Shared Data Name')
    description = models.TextField(verbose_name='Shared Data Description')
    uuid = UUIDField(auto=True, hyphenate=True, blank=True,
                     null=True)  # defaults to v.4
    # report = models.ForeignKey(Report)
    field_lookup = models.TextField(verbose_name='Field Lookup JSON')
    creation_date = models.DateField(verbose_name='Creation Date',
                                     default=datetime.date.today)
    inactive_date = models.DateField(verbose_name='Inactive Date')
    shared_recipient = models.ManyToManyField(Contact,
                                              verbose_name='Shared Recipient')
    user = models.ForeignKey(User, verbose_name="Project User")

    def __unicode__(self):
        return str(self.uuid)

    class Meta:
        verbose_name_plural = 'Shared Data'


class HotListGene(models.Model):
    name = models.CharField(max_length=32, verbose_name='HotList Gene Name')


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    viewable_studies = models.ManyToManyField(Study)


class Status(models.Model):
    bnid = models.ForeignKey(Bnid)
    study = models.ForeignKey(Study)
    sample = models.ForeignKey(Sample)
    submit_date = models.DateField(verbose_name='Submit for Sequence Date', blank=True, null=True)
    sequence_date = models.DateField(verbose_name='Sequence Date', blank=True, null=True)
    align_date = models.DateField(verbose_name='Align Date', blank=True, null=True)
    analysis_date = models.DateField(verbose_name='Date Analyzed', blank=True, null=True)
    status = models.CharField(max_length=256, verbose_name='Sample Status', default='Keys generated')

    def __str__(self):
        return '{}: {}'.format(str(self.bnid), str(self.status))

    class Meta:
        verbose_name_plural = 'Statuses'

templates/viewer/cards/cards.html
{% load staticfiles %}
<div>
<!------------------->
<!-- Sidebar Cards -->
<!------------------->
{% if 'reportSummary' in cards %}
    <div class="igsbviewer-card" data-name="reportSummary">
        <div class="igsbviewer-card-heading">
            {{ reports.first.name }}
        </div>
        <div class="igsbviewer-card-content">
            <button type="button" class="btn btn-sm btn-primary report-view-btn">
                <span class="fa fa-file-text-o"></span>&nbsp;&nbsp;
                Report View
            </button><br/><br/>
            <button type="button" class="btn btn-sm btn-primary gene-view-btn">
                <span class="fa fa-file-text-o"></span>&nbsp;&nbsp;
                Gene View
            </button><br/><br/>
            <button type="button" class="btn btn-sm btn-primary variant-view-btn">
                <span class="fa fa-file-text-o"></span>&nbsp;&nbsp;
                Variant View
            </button><br/>
        </div>
        <script src="{% static 'js/cards/reportSummary.js' %}" async></script>
    </div>
{% endif %}

{% if 'reportMultiple' in cards %}
    <div class="igsbviewer-card" data-name="reportMultiple">
        <div class="igsbviewer-card-heading">
            Summary for Multiple Reports
        </div>
        <div class="igsbviewer-card-content">
            <p>Reports in this summary: {{ reports_list_string }}</p>
            <button type="button" class="btn btn-sm btn-primary report-view-btn">
                <span class="fa fa-file-text-o"></span>&nbsp;&nbsp;
                Report View
            </button><br/><br/>
            <button type="button" class="btn btn-sm btn-primary gene-view-btn">
                <span class="fa fa-file-text-o"></span>&nbsp;&nbsp;
                Gene View
            </button><br/><br/>
            <button type="button" class="btn btn-sm btn-primary variant-view-btn">
                <span class="fa fa-file-text-o"></span>&nbsp;&nbsp;
                Variant View
            </button><br/>
        </div>
        <script src="{% static 'js/cards/reportMultiple.js' %}" async></script>
    </div>
{% endif %}

{% if 'geneList' in cards %}
    <div class="igsbviewer-card" style="overflow:hidden" data-name="geneList">
        <div class="igsbviewer-card-heading">
            Gene List
        </div>
        <div class="igsbviewer-card-content">
            {% for one in gene_list %}
            {% if forloop.counter|divisibleby:4 %}
            <div class="row">
            {% endif %}
                <div class="col-sm-3 gene-name3" data-name="{{ one }}">
                    {{ one }}
                </div>
            {% if forloop.counter|divisibleby:4 %}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        <script src="{% static 'js/cards/geneList.js' %}" async></script>
    </div>
{% endif %}

<!----------------------------->
<!-- Span Both Columns Cards -->
<!----------------------------->
{% if 'geneProfile' in cards %}
    <div class="igsbviewer-card" data-name="geneProfile">
        <div class="igsbviewer-card-heading">
            Gene Profile for {{ gene.name }}
        </div>
        <div class="igsbviewer-card-content">
            Number of {{ gene.name }} in this report: {{ gene.count }}<br/>
            {{ gene.mutations }}
        </div>
    </div>
{% endif %}

<!----------------------->
<!-- Left Column Cards -->
<!----------------------->
{% if 'studyDescription' in cards %}
    <div class="igsbviewer-card" data-name="studyDescription">
        <div class="igsbviewer-card-heading">
            Study Description
        </div>
        <div class="igsbviewer-card-content">
            <p>{{ reports.first.study.name }}</p>
            <p>{{ reports.first.study.description }}</p>
        </div>
    </div>
{% endif %}

{% if 'scrap' in cards %}
    <div class="igsbviewer-card" style="height:220px" data-name="scrap">
        <div class="igsbviewer-card-content">
            <p>Content</p>
        </div>
    </div>
{% endif %}

<!------------------------>
<!-- Right Column Cards -->
<!------------------------>
{% if 'samplesDescription' in cards %}
    <div class="igsbviewer-card" data-name="samplesDescription">
        <div class="igsbviewer-card-heading">
            Samples in {{ reports.first.name }}
        </div>
        <div class="igsbviewer-card-content">
            {% for sample in reports.first.study.sample_set.all %}
            <p>{{ sample }}<br/>{{ sample.description }}</p>
            {% endfor %}
        </div>
    </div>
{% endif %}

{% if 'sample1' in cards %}
    <div class="igsbviewer-card" data-name="sample1">
        <div class="igsbviewer-card-heading" style="background:url('http://img15.deviantart.net/7b8e/i/2010/205/3/4/a_tree_a_mountain_and_blue_sky_by_guyalt11.jpg');background-size:cover;background-position:center;background-repeat:no-repeat">
            These mountains are nice to look at<br/>
            <span style="margin-left:20%">It makes for a nice visual effect</span>
        </div>
        <div class="igsbviewer-card-content igsbviewer-centered">
            <p>Centered Content</p>
        </div>
    </div>
{% endif %}

{% if 'sample2' in cards %}
    <div class="igsbviewer-card" data-name="sample2">
        <div class="igsbviewer-card-heading">
            This is the Genome
            <span class="fa fa-flag" style="float:right"></span>
        </div>
        <div class="igsbviewer-card-content">
            <p>{{ reports.0.genome.name }}</p>
        </div>
    </div>
{% endif %}

{% if 'sample3' in cards %}
    <div class="igsbviewer-card" data-name="sample3">
        <div class="igsbviewer-card-content">
            This is just content, no header
        </div>
    </div>
{% endif %}

{% if 'refalleleratio' in cards %}
    <div class="igsbviewer-card" data-name="refalleleratio" data-chart-name="refalleleratio">
        <div class="igsbviewer-card-heading">Reference Allele Ratio</div>
        <div class="igsbviewer-card-chart">
            <span class="fa fa-circle-o-notch fa-spin fa-2x"></span>
        </div>
        <i class="chart-vars" data-report-id="{{ report_ids_json }}"></i>
    </div>
{% endif %}

{% if 'effectratio' in cards %}
    <div class="igsbviewer-card" data-name="effectratio" data-chart-name="effectratio">
        <div class="igsbviewer-card-heading">Effect Ratio</div>
        <div class="igsbviewer-card-chart">
            <span class="fa fa-circle-o-notch fa-spin fa-2x"></span>
        </div>
        <i class="chart-vars" data-report-id="{{ report_ids_json }}"></i>
    </div>
{% endif %}

{% if 'topfivegenes' in cards %}
    <div class="igsbviewer-card" data-name="topfivegenes" data-chart-name="topfivegenes">
        <div class="igsbviewer-card-heading">Top 5 Genes</div>
        <div class="igsbviewer-card-chart">
            <span class="fa fa-circle-o-notch fa-spin fa-2x"></span>
        </div>
        <i class="chart-vars" data-report-id="{{ report_ids_json }}"></i>
{#        <script src="{% static 'js/charts/topfivegenes.js' %}" async></script>#}
    </div>
{% endif %}

{% if 'qualitative_map' in cards %}
    <div class="igsbviewer-card" data-name="qualitative_map" data-chart-name="qualitative_map">
        <div class="igsbviewer-card-heading">Variants in Genes of Interest</div>
        <div class="igsbviewer-card-chart">
            <span class="fa fa-circle-o-notch fa-spin fa-2x"></span>
        </div>
        <i class="chart-vars" data-report-id="{{ report_ids_json }}" data-genes='[]'></i>
    </div>
{% endif %}

{% if 'miguelisafunnyguy' in cards %}
    <div class="igsbviewer-card" data-name="miguelisafunnyguy">
        <div class="igsbviewer-card-heading">Miguel is fun!</div>
        <div class="igsbviewer-card-content">
            But is he really?
        </div>
    </div>
{% endif %}

</div>

templates/viewer/cards/cards_control_buttons.html
<span class="fa fa-remove" style="float:right;cursor:pointer;color:#1a242f"></span>
<span class="fa fa-minus" style="float:right;margin-right:0.8em;cursor:pointer;color:#1a242f"></span>