urls.py
from django.conf.urls import patterns, url
from django.conf import settings
from django.conf.urls.static import static

import views

urlpatterns = patterns('',
                       # Access pages
                       url(r'^$', views.index, name='viewer_index'),
                       url(r'^register/$', views.register, name='viewer_register'),
                       url(r'^login/$', views.user_login, name='viewer_login'),
                       url(r'^logout/$', views.user_logout, name='viewer_logout'),
                       url(r'^restricted/$', views.restricted,
                           name='viewer_restricted'),
                       url(r'^users/change-password/', 'django.contrib.auth.views.password_change',
                           {
                               'template_name': 'viewer/user/change_password.html',
                               'post_change_redirect': '/viewer/users/change-password-done/',
                           }, name='viewer_change_password'),
                       url(r'^users/change-password-done/', 'django.contrib.auth.views.password_change_done',
                           {
                               'template_name': 'viewer/user/change_password_done.html'
                           }, name='change-password-done'),

                       url(r'^populate-sidebar/$', views.populate_sidebar, name='populate_sidebar'),

                       # Errors
                       url(r'^error/no_project/$', views.no_project, name='no_project'),
                       # Project
                       url(r'^project/$', views.manage_project,
                           name='manage_project'),
                       url(r'^project/new_project/$',
                           views.new_project, name='new_project'),
                       url(r'^project/edit_project/(?P<project_id>\d+)/$',
                           views.edit_project, name='edit_project'),
                       url(r'^get_all_projects/$', views.get_all_projects,
                           name='get_all_projects'),


                       # Bnid
                       url(r'^get_bnids_by_study/(?P<study_id>\d+)/$',
                           views.get_bnids_by_study, name='get_bnids_by_study'),
                       url(r'^get_studies/$',
                           views.get_studies, name='get_studies'),

                       # Sample
                       url(r'delete_sample/(?P<sample_id>\d+)/$', views.delete_sample,
                           name='delete_sample'),
                       url(r'^get_samples/(?P<study_id>\d+)/$', views.get_samples,
                           name='get_samples'),

                       # Metadata
                       url(r'^metadata/$', views.manage_metadata, name='manage_metadata'),
                       url(r'^metadata/(?P<set_viewing_project_pk>\d+)/$', views.manage_metadata,
                           name='manage_metadata_set_viewing_project_pk'),
                       url(r'^metadata/new_metadata/$', views.new_metadata, name='new_metadata'),
                       url(r'^metadata/edit_metadata/(?P<sample_id>\d+)/$',
                           views.edit_metadata, name='edit_metadata'),

                       # Status
                       url(r'^status/$', views.manage_status, name='manage_status'),
                       url(r'^status/update_status/$', views.update_status, name='update_status'),
                       url(r'^status/check_status/$', views.check_status, name='check_status'),
                       url(r'^status/get_all_statuses/$', views.get_all_statuses, name='get_all_statuses'),
                       url(r'^status/get_stats/(?P<dname>\w+)/(?P<bnid>\d+-\d+)/$', views.get_stats, name='get_stats'),
                       url(r'^status/ajax_rows/(?P<start>\d+)/(?P<stop>\d+)/$', views.manage_status_ajax_rows,
                           name='manage_status_ajax_rows'),

                       # Study
                       url(r'^study/$', views.manage_study, name='manage_study'),
                       url(r'^study/(?P<set_viewing_project_pk>\d+)$', views.manage_study,
                           name='manage_study_set_viewing_project_pk'),
                       url(r'^study/new_study/$', views.new_study, name='new_study'),
                       url(r'^study/edit_study/(?P<study_id>\d+)/$',
                           views.edit_study, name='edit_study'),
                       url(r'^study/delete_study/(?P<study_id>\d+)/$',
                           views.delete_study, name='delete_study'),

                       # Report
                       # url(r'^report/$', views.manage_report,
                       #     name='manage_report'),
                       # url(r'^report/(?P<set_viewing_project_pk>\d+)/$', views.manage_report,
                       #     name='manage_report_set_viewing_project_pk'),
                       # url(r'^report/ajax_rows/(?P<start>\d+)/(?P<stop>\d+)/$', views.manage_report_ajax_rows,
                       #     name='manage_report_ajax_rows'),
                       # url(r'^report/edit_report/(?P<report_id>\d+)/$',
                       #     views.edit_report, name='edit_report'),
                       # url(r'report/view_report/(?P<file_id>\d+)/$',
                       #     views.view_report, name='view_report'),
                       # url(r'^report/upload_report/$', views.upload_report,
                       #     name='upload_report'),
                       # url(r'^report/delete_report/(?P<report_id>\d+)/$', views.delete_report,
                       #     name='delete_report'),
                       # url(r'^load_variants/(?P<report_id>\d+)/$', views.load_variants,
                       #     name='load_variants'),
                       # url(r'^report/zip-and-download/', views.zip_and_download, name='zip_and_download'),
                       # url(r'^report/get_info/$', views.report_info_get, name='report_info_get'),
                       #
                       # # Share
                       # url(r'^shared/view/(?P<shared_data_uuid>[\da-f\-]+)/$', views.view_shared_data,
                       #     name='view_shared_data'),
                       # url(r'^shared/share_report/$', views.share_report, name='share_report_post'),
                       # # url(r'^shared/share_report/(?P<report_id>\d+)/$', views.share_report, name='share_report'),
                       # url(r'^error/shared_data_expired/$',
                       #     views.view_share_data_expired, name='shared_data_expired'),
                       # url(r'^error/shared_data_dne/$', views.view_share_data_dne, name='shared_data_dne'),
                       #
                       # url(r'^files/(?P<path>.*)$',
                       #     'django.views.static.serve',
                       #     {'document_root': settings.MEDIA_ROOT}),

                       # Contact
                       url(r'^contact/$', views.manage_contact,
                           name='manage_contact'),
                       url(r'^contact/(?P<set_viewing_project_pk>\d+)/$', views.manage_contact,
                           name='manage_contact_set_viewing_project_pk'),
                       url(r'^contact/new_contact/$', views.new_contact,
                           name='new_contact'),
                       url(r'^contact/new_contact_from_share/$', views.new_contact_from_share,
                           name='new_contact'),
                       url(r'^contact/edit_contact/(?P<contact_id>\d+)/$', views.edit_contact,
                           name='edit_contact'),
                       url(r'^contact/delete_contact/(?P<contact_id>\d+)/$', views.delete_contact,
                           name='delete_contact'),
                       url(r'^contact/get_contacts_json/(?P<project_id>\d+)/$', views.get_contacts_json,
                           name='get_contacts'),

                       # Search
                       # url(r'^search/$', views.search_reports, name='search_reports'),
                       # url(r'^search/(?P<set_viewing_project_pk>\d+)/$', views.search_reports,
                       #     name='search_reports_set_viewing_project_pk'),
                       # url(r'^ajax_search_reports/(?P<search_col>\S+)/(?P<search_term>\S+)/(?P<search_type>\S+)/$',
                       #     views.ajax_search_reports, name='ajax_search_reports'),
                       # url(r'^ajax_search_reports/(?P<search_col>\S+)/(?P<search_term>\S+)/(?P<search_type>\S+)/(?P<reports_ids>\S+)/$',
                       #     views.ajax_search_reports, name='ajax_search_reports'),
                       #
                       #
                       # # Info
                       # url(r'^info/$', views.info_many, name='info_many'),
                       # url(r'^info/(?P<report_id>\d+)/$', views.info, name='info'),
                       # url(r'^cards/get/$', views.get_cards, name='get_cards'),
                       # # url(r'^cards/gene/(?P<report_id>\d+)/$', views.cards, name='cards_report'),
                       # url(r'^get_series_data/$', views.get_series_data, name='get_series_data')
                       #
                       ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

models.py
import datetime

from django.contrib.auth.models import User
from django.db import models
from uuidfield import UUIDField


class Project(models.Model):
    name = models.CharField(max_length=64, verbose_name="Project Name")
    description = models.CharField(max_length=2048,
                                   verbose_name="Project Description", blank=True)
    creation_date = models.DateTimeField('Date Created', auto_now=True,
                                         blank=True)
    user = models.ManyToManyField(User, blank=True,
                                  verbose_name="Project User")

    def __unicode__(self):
        return self.name


class Study(models.Model):
    name = models.CharField(max_length=64, verbose_name="Study Name", unique=True)
    project = models.ForeignKey(Project)
    description = models.CharField(max_length=256,
                                   verbose_name="Study Description",
                                   blank=True)
    creation_date = models.DateTimeField('Date Created', auto_now=True,
                                         blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Studies'


class Caller(models.Model):
    name = models.CharField(max_length=64, verbose_name="Caller Name")

    def __str__(self):
        return self.name


class Genome(models.Model):
    name = models.CharField(max_length=64, verbose_name="Genome")

    def __str__(self):
        return self.name


class Sample(models.Model):
    name = models.CharField(max_length=48, verbose_name='Sample Name', unique=True)
    description = models.CharField(max_length=256,
                                   verbose_name="Sample Description",
                                   blank=True)
    cellularity = models.CharField(max_length=8, verbose_name='% Cellularity',
                                   blank=True)
    study = models.ForeignKey(Study)
    creation_date = models.DateTimeField('Date Created', auto_now=True,
                                         blank=True)

    def __str__(self):
        return str(self.name)


class Bnid(models.Model):
    sample = models.ForeignKey(Sample)
    bnid = models.CharField(max_length=12, verbose_name='Bionimbus ID')
    description = models.CharField(max_length=256, verbose_name='Description',
                                   blank=True)
    library_type = models.CharField(max_length=32, verbose_name='Sequencing library type', blank=True)
    creation_date = models.DateTimeField('Date Created', auto_now=True,
                                         blank=True)

    def __str__(self):
        return '{} ({})'.format(str(self.sample), str(self.bnid))


# class Report(models.Model):
#     caller = models.ForeignKey(Caller)
#     study = models.ForeignKey(Study)
#     name = models.CharField(max_length=256, verbose_name='Report Name', default='report')
#     genome = models.ForeignKey(Genome, default=1, blank=True)
#     upload_date = models.DateTimeField('Date Uploaded', auto_now=True)
#     bnids = models.ManyToManyField(Bnid, verbose_name='Bionimbus ID', blank=True)
#     report_file = models.FileField('Report File', upload_to='', blank=True,
#                                    null=True)
#
#     def show_bnids(self):
#         return "_".join([a.bnid for a in self.bnids.all()])
#
#     def __str__(self):
#         return str(self.report_file)


# class Variant(models.Model):
#     report = models.ForeignKey(Report)
#     chrom = models.CharField(max_length=24, verbose_name='Chrom')
#     pos = models.IntegerField(verbose_name='Position', null=True)
#     ref = models.CharField(max_length=256, verbose_name='Reference Allele',
#                            blank=True, null=True)
#     alt = models.CharField(max_length=256, verbose_name='Alternate Allele',
#                            blank=True, null=True)
#     normal_ref_count = models.IntegerField(verbose_name='Normal Ref Count',
#                                            blank=True, null=True)
#     normal_alt_count = models.IntegerField(verbose_name='Normal Alt Count',
#                                            blank=True, null=True)
#     pct_normal_alt = models.FloatField(verbose_name='%_Normal_Alt',
#                                        blank=True, null=True)
#     tumor_ref_count = models.IntegerField(verbose_name='Tumor Ref Count',
#                                           blank=True, null=True)
#     tumor_alt_count = models.IntegerField(verbose_name='Tumor Alt Count',
#                                           blank=True, null=True)
#     pct_tumor_alt = models.FloatField(verbose_name='%_Tumor_Alt',
#                                       blank=True, null=True)
#     tn_pct_alt_ratio = models.FloatField(verbose_name='T/N % alt ratio',
#                                          blank=True, null=True)
#     gene_name = models.CharField(max_length=32, verbose_name='Gene Name',
#                                  blank=True, null=True)
#     extra_info = models.CharField(verbose_name='Extra Info', blank=True,
#                                   null=True, max_length=20000)
#
#     def __str__(self):
#         return "{}:{}{}>{}".format(self.chrom, self.pos, self.ref, self.alt)


class Contact(models.Model):
    full_name = models.CharField(max_length=256, verbose_name='Full Name')
    email = models.EmailField(verbose_name='Email')
    project = models.ForeignKey(Project, verbose_name='Project',
                                blank=True, null=True)

    def __unicode__(self):
        return '"{}" <{}>'.format(self.full_name, self.email)


class SharedData(models.Model):
    name = models.CharField(max_length=128, verbose_name='Shared Data Name')
    description = models.TextField(verbose_name='Shared Data Description')
    uuid = UUIDField(auto=True, hyphenate=True, blank=True,
                     null=True)  # defaults to v.4
    # report = models.ForeignKey(Report)
    field_lookup = models.TextField(verbose_name='Field Lookup JSON')
    creation_date = models.DateField(verbose_name='Creation Date',
                                     default=datetime.date.today)
    inactive_date = models.DateField(verbose_name='Inactive Date')
    shared_recipient = models.ManyToManyField(Contact,
                                              verbose_name='Shared Recipient')
    user = models.ForeignKey(User, verbose_name="Project User")

    def __unicode__(self):
        return str(self.uuid)

    class Meta:
        verbose_name_plural = 'Shared Data'


class HotListGene(models.Model):
    name = models.CharField(max_length=32, verbose_name='HotList Gene Name')


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    viewable_studies = models.ManyToManyField(Study)


class Status(models.Model):
    bnid = models.ForeignKey(Bnid)
    study = models.ForeignKey(Study)
    sample = models.ForeignKey(Sample)
    submit_date = models.DateField(verbose_name='Submit for Sequence Date', blank=True, null=True)
    sequence_date = models.DateField(verbose_name='Sequence Date', blank=True, null=True)
    align_date = models.DateField(verbose_name='Align Date', blank=True, null=True)
    analysis_date = models.DateField(verbose_name='Date Analyzed', blank=True, null=True)
    status = models.CharField(max_length=256, verbose_name='Sample Status', default='Keys generated')

    def __str__(self):
        return '{}: {}'.format(str(self.bnid), str(self.status))

    class Meta:
        verbose_name_plural = 'Statuses'

templates/viewer/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <title>Variant Viewer</title>
        <!-- JQuery -->
        <script src="{% static 'js/lib/jquery-2.1.3.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/lib/jquery-ui.min.js' %}" type="text/javascript"></script>

        <!-- Bootstrap -->
        <link href="{% static 'css/bootstrap.flatly.min.css' %}" rel="stylesheet" media="screen">
        <script src="{% static 'js/lib/bootstrap.min.js' %}" type="text/javascript"></script>

        <!-- animate.css -->
        <link href="{% static 'css/animate.min.css' %}" rel="stylesheet" media="screen">

        <!-- jBox -->
        <link href="{% static 'css/jBox.css' %}" rel="stylesheet" media="screen">
        <script src="{% static 'js/lib/jBox.min.js' %}" type="text/javascript"></script>

        <!-- Highcharts -->
        <script src="{% static 'js/lib/highcharts.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/lib/heatmap.js' %}" type="text/javascript"></script>

        <!-- Material sidebar -->
        <link href="{% static 'css/material-sidebar.css' %}" rel="stylesheet" media="screen">
        <link href="{% static 'css/ripples.css' %}" rel="stylesheet" media="screen">
        <script src="{% static 'js/lib/materialSidebar.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/base/material-sidebar.js' %}" type="text/javascript"></script>

        <!-- DynaTables -->
        <script src="{% static 'js/lib/jquery.dynatable.js' %}"></script>
        <link href="{% static 'css/jquery.dynatable.css' %}" rel="stylesheet"/>

        <!-- Font Awesome -->
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">

        <!-- Moment JS datetime library -->
        <script src="{% static 'js/lib/moment.min.js' %}" type="text/javascript"></script>

        <!-- Custom js and css -->
        <link href="{% static 'css/viewer.css' %}" rel="stylesheet" media="screen">

        <!-- Material Effects -->
        <script src="{% static 'js/lib/material.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/lib/ripples.min.js' %}" type="text/javascript"></script>
        <script>$.material.init();</script>

        {% block extra_js %}
        {% endblock %}
    </head>
    <body style="padding-top: 70px">
    {% block material-sidebar %}
        {% include 'viewer/sidebar/material-sidebar.html' %}
    {% endblock material-sidebar %}

    <!-- Top Navigation Bar -->
    <nav class="navbar navbar-default navbar-fixed-top navbar-material-light-blue">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand siddebar-toggle" id="burger-toggle" style="cursor:pointer">
                    <span class="fa fa-bars"></span>&nbsp;&nbsp;
                    <img style="display:inline-block;max-height:46px;margin-top:-13px;margin-left:12px" src="{% static 'img/blue_logo.png' %}">
                </a>
            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'viewer_index' %}">Home</a></li>
                    {% if perms.viewer.add_project %}
                    <li><a href="{% url 'manage_project' %}">Projects</a></li>
                    {% endif %}
                    {% if perms.viewer.add_study %}
                    <li><a href="{% url 'manage_study' %}">Studies</a></li>
                    {% endif %}
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'manage_metadata' %}">Metadata</a></li>
                    <li><a href="{% url 'manage_status' %}">Sample Status</a></li>
                    <li><a href="https://igsb.uchicago.edu/cbioportal">U Chicago cbioportal</a></li>
                    {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li><p class="navbar-text">Logged in: {% if user.first_name %}{{ user.first_name }}{% else %}{{ user.username }}{% endif %}</p></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            My Account <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'viewer_change_password' %}">Change Password</a></li>
                        </ul>
                    </li>
                    <li><a href="{% url 'viewer_logout' %}">
                        <span class="fa fa-sign-out"></span>&nbsp;&nbsp;Logout
                    </a></li>
                    {% else %}
                    <li><a href="{% url 'viewer_login' %}">
                        <span class="fa fa-sign-in"></span>&nbsp;&nbsp;Login
                    </a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock content%}

    </body>
</html>

templates/viewer/index.html
{% extends "viewer/base.html" %}
{% load staticfiles %}

{% block content %}
<style>
body{
    background-image: url('{% static 'img/campus_city_lake_1280x800_compressed.jpg' %}');
    background-size: cover;
}
</style>
<div class="container">
    <div class="row viewer-box" style="margin-top:100px">
        <h1 style="margin-top:0;text-align:center">Chicago Pancreatic Cancer Initiative (CPCI) LIMS</h1>
        {% if user.is_authenticated %}
        <p>Hello, {% if user.first_name %}{{ user.first_name }}{% else %}{{ user.username }}{% endif %}!</p>
        {% endif %}
        <p>
		The purpose of this site is to act as a LIMS for NGS sequencing related to the CPCI. Studies and and related
            sample QC can be found here. Variant calls and expression-level details can be found on our local
            implementation of MSKCCs cbioportal.
	    </p>
	    <p style="text-align:center;margin-top:50px">
            {% if not user.is_authenticated %}
            <a href="{% url 'viewer_login' %}">
                <button class="btn btn-small btn-primary" style="margin-right:25px;">
                    <span class="fa fa-2x fa-sign-in"></span>
                    <span style="position:relative;top:-6px">&nbsp;&nbsp;Login</span>
                </button>
            </a>
            <a href="{% url 'viewer_register' %}">
                <button class="btn btn-small btn-primary">
                    <img style="display:inline-block;max-height:30px" src="{% static 'img/blue_logo.png' %}">
                    &nbsp;&nbsp;Register Here
                </button>
            </a>
            {% endif %}

        </p>
    </div>
</div>
{% endblock %}